baseURL = "https://bstreete.github.io/"
languageCode = "en-us"
title = "Brayden's Recipes"
theme = "m10c"
description = ''
paginate = 20

[params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"

# Overwrite the default taxonomy structure
[taxonomies]
    tag = "tags"
    author = "author"
