baseURL = "https://bstreete.github.io/public/"
languageCode = "en-us"
title = "Brayden's Recipes"
theme = "m10c"
description = ''
paginate = 20

## Left for posterity, default color scheme is the pleasant green/gray
[params.style]
  darkestColor = "#161616"
  darkColor = "#1e1e1e"
  primaryColor = "#31a98b"
  lightColor = "#a8a8a8"
  lightestColor = "#cccccc"

# Overwrite the default taxonomy structure
[taxonomies]
    tag = "tags"
    author = "author"
